version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: laser_cutting_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: laser_cutting_db
      MYSQL_USER: laser_user
      MYSQL_PASSWORD: laser_pass
    ports:
      - "3330:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laser_cutting_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123456
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - "8880:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: